spring:
  datasource:
    url: jdbc:mariadb://127.0.0.1:3307/realworld_db?serverTimezone=Asia/Seoul&useSSL=false&characterEncoding=UTF-8
    username: root
    password: root123
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      maximum-pool-size: 4
      minimum-idle: 1

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.type: trace
    org.hibernate.SQL: debug

server:
  port: 8080

token:
  sessionTime: 60
  signKey: jwt.secret